name: wearapp
description: Data Gathering in Emotion and Affect Experiments with Wearables.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.5
  flutter_screenutil: ^2.3.1
  google_fonts: ^1.1.0
  path_provider: ^1.6.14
  flutter_blue: ^0.7.2
  toast: ^0.1.5
  intl: ^0.16.1
  encrypt: ^4.1.0
  flutter_custom_clippers: ^1.1.2
  syncfusion_flutter_charts: ^18.3.50
  bitalino: ^1.1.1+1
  flutter_bluetooth_serial: ^0.2.2
  csv: ^4.1.0
  share: ^0.6.5+4
  syncfusion_flutter_sliders: ^18.4.31-beta

  # simple_permissions: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
